---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-blobfuse-proxy
  namespace: {{ .Release.Namespace }}
{{ include "blob.labels" . | indent 2 }}
spec:
  selector:
    matchLabels:
      app: csi-blobfuse-proxy
  template:
    metadata:
{{ include "blob.labels" . | indent 6 }}
      labels:
        app: csi-blobfuse-proxy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      priorityClassName: system-node-critical
      tolerations:
        - operator: "Exists"
      {{- include "blob.pullSecrets" . | indent 6 }}
      containers:
        - name: proxy
          image: "{{ .Values.image.blobfuseproxy.repository }}:{{ .Values.image.blobfuseproxy.tag }}"
          imagePullPolicy: {{ .Values.image.blobfuseproxy.pullPolicy }}
          args:
            - "--blobfuse-proxy-endpoint=$(BLOBFUSE_PROXY_ENDPOINT)"
          env:
            - name: BLOBFUSE_PROXY_ENDPOINT
              value: unix://csi/blobfuse-proxy.sock
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          resources:
            limits:
              cpu: 2
              memory: 2100Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - hostPath:
            path: {{ .Values.kubelet.linuxPath }}/plugins/blob.csi.azure.com
            type: DirectoryOrCreate
          name: socket-dir
---
